export const STORE_SEARCH = "STORE_SEARCH";

export const REQUEST_SIGNUP_START = "REQUEST_SIGNUP_START";
export const REQUEST_SIGNUP_SUCCESS = "REQUEST_SIGNUP_SUCCESS";
export const REQUEST_SIGNUP_FAIL = "REQUEST_SIGNUP_FAIL";

